openapi: 3.0.1
info:
  title: Network API Gateway Spec
  description: 'Schema for objects passed between API Gateway, its SDKs, and client code'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: landon.cox@microsoft.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.2.0
externalDocs:
  description: Project git repo
  url: 'https://github.com/lpcox/gateway-control-plane'
paths:
  /getnetworks:
    $ref: paths/getnetworks.yaml
  /sessionstart:
    $ref: paths/sessionstart.yaml
  /sessionexpire:
    $ref: paths/sessionexpire.yaml
  /getues:
    $ref: paths/getues.yaml
  /getedges:
    $ref: paths/getedges.yaml
  /getproperties:
    $ref: paths/getproperties.yaml
  /pubsubstart:
    $ref: paths/pubsubstart.yaml
